annotations:
  category: ApplicationServer
  images: |
    - name: jmx-exporter
      image: docker.io/bitnami/jmx-exporter:0.19.0-debian-11-r84
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r77
    - name: tomcat
      image: docker.io/bitnami/tomcat:10.1.13-debian-11-r24
  licenses: Apache-2.0
apiVersion: v2
appVersion: 10.1.13
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Tomcat is an open-source web server designed to host and run Java-based
  web applications. It is a lightweight server with a good performance for applications
  running in production environments.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/tomcat/img/tomcat-stack-220x234.png
keywords:
- tomcat
- java
- http
- web
- application server
- jsp
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: tomcat
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/tomcat
version: 10.10.4
